---
# How to run:
# ansible-playbook -i \
#     .vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory \
#     database.yml

- name: Database
  # Target all hosts
  hosts: all
  # Become default root user
  become: true
  vars:
    db_name: ansi_db
  tasks:
    - name: Utils Present
      ansible.builtin.package:
        name: python3-psycopg2
        state: present

    - name: Create Database
      become: true
      # Become postgres user
      become_user: postgres
      community.postgresql.postgresql_db:
        name: "{{ db_name }}"
        state: present
