---
# This file is provisioned upon `vagrant up` (via Vagrantfile),
# then it installs PostgreSQL and Docker to the guest OS.

# Or run as `vagrant provision`

# Or:
# ansible-playbook -i \
#     .vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory \
#     playbook.yml

# Must be run from control node

- hosts: all
  become: true

  vars_files:
    - variables.yml

  pre_tasks:
    # Basic tools
    - name: Install Basic Tools
      ansible.builtin.apt:
        name:
          - htop
          - net-tools
        state: present

    # PostgreSQL's prerequisites
    - name: Install PostgreSQL Prerequisites
      ansible.builtin.apt:
        name:
          - libpq-dev
          - postgresql
          - postgresql-contrib
          - python3-psycopg2
        state: present

    # Docker's prerequisites
    - name: Install Docker Prerequisites
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present

  tasks:
    # Setup PostgreSQL
    - name: Check PostgreSQL Init
      ansible.builtin.stat:
        # Register pg_hba.conf to variable
        path: "{{ postgresql_data_dir }}/pg_hba.conf"
      register: postgres_data

    - name: Empty PostgreSQL Data
      ansible.builtin.file:
        path: "{{ postgresql_data_dir }}"
        state: absent
      when: not postgres_data.stat.exists

    - name: Initialize PostgreSQL
      ansible.builtin.shell: "{{ postgresql_bin_path }}/initdb -D {{ postgresql_data_dir }}"
      # Become `postgres` user
      become: true
      become_user: postgres
      # Run if data directory nonexistent
      when: not postgres_data.stat.exists

    - name: Start PostgreSQL Service
      ansible.builtin.service:
        name: postgresql
        state: started
        enabled: true

    # Begin installing Docker
    - name: Add Docker apt-key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg

    - name: Add Docker Repository
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable

    - name: Install Docker
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        # Update sources after adding Docker repo
        update_cache: yes

    - name: Add User Permissions
      # Add Vagrant user to Docker group
      ansible.builtin.shell: "usermod -aG docker vagrant"
