---
# This file is provisioned upon `vagrant up` (via Vagrantfile),
# then it installs PostgreSQL and Docker to the guest OS.

# Or run as `vagrant provision`
# Or `ansible-playbook playbook.yml`
# Must be run from control node

- hosts: all
  become: true

  # vars_files:
  #   - variables.yml

  pre_tasks:
    # Basic tools
    - name: Install Basic Tools
      ansible.builtin.apt:
        name:
          - htop
          - net-tools
        state: present

    # Postgresql's prerequisites
    - name: Install PostgreSQL Prerequisites
      ansible.builtin.apt:
        name:
          - libpq-dev
          - postgresql
          - postgresql-contrib
          - python3-psycopg2
        state: present

    # Docker's prerequisites
    - name: Install Docker Prerequisites
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present

    # Begin installing Docker
    - name: Add Docker apt-key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
    - name: Add Docker Repository
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
    - name: Install Docker
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        # Update sources after adding Docker repo
        update_cache: yes
    - name: Add User Permissions
      # Add Vagrant user to Docker group
      ansible.builtin.shell: "usermod -aG docker vagrant"
